##############################################################
# Bayesian Networks
# 4/4/2021
# created by T. Gärtner (thomas.gaertner@student.hpi.de)
##############################################################



#' Prepare Dag
#' @description This function reformat a DAG from DAGitty to bn.learn DAG
#' @param dag DAG in a DAGitty format
#' @return bnlearn graph based on DAGitty graph
#' @examples
#' load(simpatdag)
#' bn.prep.dag(simpatdag)
#' @export
bn.prep.dag <- function(dag){
  exposure <- exposures(dag)
  outcome <- outcomes(dag)
  bn.dag <- empty.graph(nodes = names(dag))
  edges <- edges(dag)
  edges$from <- edges$v
  edges$to <- edges$w
  edges[] <- lapply(edges,as.character)
  arcs(bn.dag) = edges[,c("from","to")]
  plot(bn.dag, main = "Transformed Bn DAG")
  return(list(dag = bn.dag, exposure = exposure, outcome = outcome))
}


#' Bayesian Network Analysis
#' @description This function is an Interface to the fitting function for Bayesian Networks from bnlearn
#' @param dag DAG generated by
#' @param data R data frame to fit the Bayesian network
#' @param method Method used to analyze. Default is 'bayes'. Alternative is 'mle'
#' @return bn.fit object
#' @examples
#' load(simpatdag)
#' bn.prep.dag(simpatdag)
#' @export
fit.bn.dag <- function(dag, data, method){
  if(missing(method)){
    method <- "bayes"
  }
  fit <- bn.fit(dag$dag, data, method = method)
  return(fit)
}


